src/Entity/Todo.php
<?php

namespace App\Entity;

use App\Repository\TodoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TodoRepository::class)]
class Todo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $due_at = null;

    #[ORM\Column]
    private ?bool $isImportant = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDueAt(): ?\DateTimeImmutable
    {
        return $this->due_at;
    }

    public function setDueAt(?\DateTimeImmutable $due_at): self
    {
        $this->due_at = $due_at;

        return $this;
    }

    public function isIsImportant(): ?bool
    {
        return $this->isImportant;
    }

    public function setIsImportant(bool $isImportant): self
    {
        $this->isImportant = $isImportant;

        return $this;
    }
}

src/Form/TodoType.php
<?php

namespace App\Form;

use App\Entity\Todo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TodoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('due_at')
            ->add('isImportant')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Todo::class,
        ]);
    }
}

src/Controller/TodoController.php
<?php

namespace App\Controller;

use App\Entity\Todo;
use App\Form\EditTodoType;
use App\Form\TodoType;
use App\Repository\TodoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\UX\Turbo\TurboBundle;

#[Route('/todo')]
class TodoController extends AbstractController
{
    #[Route('/', name: 'app_todo_index', methods: ['GET'])]
    public function index(TodoRepository $todoRepository): Response
    {
        return $this->render('todo/index.html.twig', [
            'todos' => $todoRepository->findBy([], ['due_at' => 'ASC']),
        ]);
    }

    #[Route('/{id}/edit', name: 'app_todo_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Todo $todo, TodoRepository $todoRepository): Response
    {
        $form = $this->createForm(EditTodoType::class, $todo, [
            'action' => $this->generateUrl('app_todo_edit', ['id' => $todo->getId()])
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $todoRepository->save($todo, true);

            return $this->redirectToRoute('app_todo_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('todo/edit.html.twig', [
            'todo' => $todo,
            'form' => $form,
        ]);
    }

    #[Route('/new', name: 'app_todo_new', methods: ['GET', 'POST'])]
    public function new(Request $request, TodoRepository $todoRepository): Response
    {
        $form = $this->createForm(TodoType::class, (new Todo())->setDueAt(new \DateTimeImmutable()), [
            'action' => $this->generateUrl('app_todo_new'),
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $todo = $form->getData();
            $todoRepository->save($todo, true);
            $request->setRequestFormat(TurboBundle::STREAM_FORMAT);

            if (TurboBundle::STREAM_FORMAT === $request->getPreferredFormat()) {
                $request->setRequestFormat(TurboBundle::STREAM_FORMAT);

                return $this->renderForm('todo/_new.stream.html.twig', ['todo' => $todo]);
            }

            return $this->redirectToRoute('app_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('todo/new.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_todo_delete', methods: ['POST'])]
    public function delete(Request $request, Todo $todo, TodoRepository $todoRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$todo->getId(), $request->request->get('_token'))) {
            $id = $todo->getId();
            $todoRepository->remove($todo, true);
            // If the request comes from Turbo, set the content type as text/vnd.turbo-stream.html and only send the HTML to update
            $request->setRequestFormat(TurboBundle::STREAM_FORMAT);

            return $this->render('todo/_delete.stream.html.twig', [
                'id' => $id,
            ]);
        }

        return $this->redirectToRoute('app_todo_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/todo/_delete.stream.html.twig
<turbo-stream action="remove" target="todo_{{ id }}">
</turbo-stream>

templates/todo/_delete_form.html.twig
<form method="post" action="{{ path('app_todo_delete', {'id': todo.id}) }}">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ todo.id) }}">
    <button class="card__link-primary">Terminer</button>
</form>

templates/todo/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/todo/_new.stream.html.twig
<turbo-stream action="append" target="todos">
    <template>
        <turbo-frame id="todo_{{ todo.id }}">
            <div class="card">
                <p class="card__title">
                    {% if todo.isImportant %}
                        <span style="color: red;">!!!</span>
                    {% endif %}
                    {{ todo.title }}
                    {% if todo.isImportant %}
                        <span style="color: red;">!!!</span>
                    {% endif %}
                </p>
                <p class="card__description">{{ todo.description }}</p>
                <p class="card__date">{{ todo.dueAt ? 'À compléter pour le ' ~ todo.dueAt|date("d-m-y") : ''}}</p>
                <div class="card__actions">
                    <a class="card__link-secondary" href="{{ path('app_todo_edit', {'id': todo.id}) }}">Modifier</a>
                    <a class="card__link-primary" href="{{ path('app_todo_edit', {'id': todo.id}) }}">Terminé</a>
                </div>
            </div>
        </turbo-frame>
    </template>
</turbo-stream>

templates/todo/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <turbo-frame id="todo_{{ todo.id }}">
        <div class="card-edit">
            {{ form_start(form) }}
                <p class="card-edit__title">
                    {{ form_widget(form.title) }}
                </p>
                <p class="card-edit__description">
                    {{ form_widget(form.description) }}
                </p>
                <p class="card-edit__date">
                    {{ form_label(form.due_at) }}
                    {{ form_widget(form.due_at) }}
                </p>
            <p>
                {{ form_label(form.isImportant) }}
                {{ form_widget(form.isImportant) }}
            </p>
            <div class="card-edit__actions">
                <button class="card-edit__update">Mettre à jour</button>
                <a class="card-edit__cancel" href="{{ path('app_todo_index')}}">Annuler</a>
            </div>
            {{ form_end(form) }}
        </div>
    </turbo-frame>
{% endblock %}

templates/todo/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="index" id="todos">
        {% for todo in todos %}
            <turbo-frame id="todo_{{ todo.id }}">
                <div class="card">
                    <p class="card__title">
                        {% if todo.isImportant %}
                            <span style="color: red;">!!!</span>
                        {% endif %}
                        {{ todo.title }}
                        {% if todo.isImportant %}
                            <span style="color: red;">!!!</span>
                        {% endif %}
                    </p>
                    <p class="card__description">{{ todo.description }}</p>
                    <p class="card__date">{{ todo.dueAt ? 'À compléter pour le ' ~ todo.dueAt|date("d-m-y") : ''}}</p>
                    <div class="card__actions">
                        <a class="card__link-secondary" href="{{ path('app_todo_edit', {'id': todo.id}) }}">Modifier</a>
                        {{ include('todo/_delete_form.html.twig') }}
                    </div>
                </div>
            </turbo-frame>
        {% else %}
            <div>
                <span>Rien à faire !</span>
            </div>
        {% endfor %}
    </div>
    <turbo-frame id="newTodoPage">
        <a class="card__link-primary newtodoaction" href="{{ path('app_todo_new') }}">Nouveau todo</a>
    </turbo-frame>

{% endblock %}

templates/todo/modal-edit.html.twig
<turbo-frame id="modal">
    <div class="modal fade" id="edit_modal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h2>Edit tweet #{{ todo.id }}</h2>
                </div>
                <turbo-frame id="modal_body" class="modal-body">
                    {{ form_start(form, {attr: {'data-turbo-frame': 'todo_' ~ todo.id }}) }}
                    {{ form_widget(form) }}
                    <button>save</button>
                    {{ form_end(form) }}

                    <script>
                        document.querySelector('.modal-body button')
                            .addEventListener('click', () => {
                                const form = document.querySelector('.modal-body form');
                                form.addEventListener('turbo:submit-end', (event) => {
                                    if (event.detail.success) {
                                        window.modal.hide();
                                    }
                                });
                            });
                    </script>

                </turbo-frame>
            </div>
        </div>
    </div>
    <script>
        window.modal = new Modal(document.getElementById('edit_modal'));
        window.modal.show();
    </script>
</turbo-frame>

templates/todo/new.html.twig
{% block body %}
    <turbo-frame id="newTodoPage">
        <div class="card-edit card-new">
            {{ form_start(form) }}
            <p class="card-edit__title">
                {{ form_widget(form.title) }}
            </p>
            <p class="card-edit__description">
                {{ form_widget(form.description) }}
            </p>
            <p class="card-edit__date">
                {{ form_label(form.due_at) }}
                {{ form_widget(form.due_at) }}
            </p>
            <p>
                {{ form_label(form.isImportant) }}
                {{ form_widget(form.isImportant) }}
            </p>
            <div class="card-edit__actions">
                <button class="card-edit__update">Ajouter</button>
                <a class="card-edit__cancel" href="{{ path('app_todo_index')}}">Annuler</a>
            </div>
            {{ form_end(form) }}
        </div>
    </turbo-frame>
{% endblock %}

templates/todo/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Todo{% endblock %}

{% block body %}
    <h1>Todo</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ todo.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ todo.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ todo.description }}</td>
            </tr>
            <tr>
                <th>Due_at</th>
                <td>{{ todo.dueAt ? todo.dueAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>IsImportant</th>
                <td>{{ todo.isImportant ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_todo_index') }}">back to list</a>

    <a href="{{ path('app_todo_edit', {'id': todo.id}) }}">edit</a>

    {{ include('todo/_delete_form.html.twig') }}
{% endblock %}